# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run Tests
permissions:
  contents: read

on:
  push:
    branches: [main, next]
  pull_request:
    branches: [main]
  schedule:
    - cron: "55 */12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Fetch Dependencies
        run: pnpm install

      - name: Test
        #        Run scheduled tests on a latest version of the game, on push - on commited in all.meta.json
        run: |
          if [ "$GITHUB_EVENT_NAME" != "push" ]; then
            pnpm test:nightly
          else
            pnpm fetch:fixtures && pnpm test
          fi

      - name: Build
        env:
          SENTRY_DSN: ${{ vars.SENTRY_DSN }}
        run: pnpm build

      - name: Upload Translation Strings
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && secrets.TRANSIFEX_SECRET != ''
        env:
          TRANSIFEX_SECRET: ${{ secrets.TRANSIFEX_SECRET }}
          TRANSIFEX_TOKEN: ${{ vars.TRANSIFEX_TOKEN }}
        run: pnpm i18n:push

      - name: Deploy ðŸš€
        if: github.event_name == 'push' && false
        uses: cloudflare/pages-action@v1
        with:
          accountId: 6f45d2e990c24e26aafd1513de56d82d
          projectName: cbn-guide
          directory: dist
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
